[ci] Adding a new test to validate new code is tested

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -88,3 +88,10 @@ jobs:
       run: |
         python${{ env.PY_VER }} -m pylint --rcfile=$(pwd)/.pylintrc gef.py tests/*/*.py
 
+    - name: Run test coverage
+      run: |
+        current_score=$(curl --silent https://hugsy.github.io/gef/coverage/gef_py.html | grep pc_cov | sed 's?.*<span class="pc_cov">\([^%]*\)%</span>?\1?g')
+        bash docs/generate-coverage-docs.sh
+        new_score=$(cat docs/coverage/gef_py.html | grep pc_cov | sed 's?.*<span class="pc_cov">\([^%]*\)%</span>?\1?g')
+        echo "Test coverage score: ${new_score}% (old ${current_score}%)"
+        test ${current_score} -gt ${new_score} && (echo "New score cannot be lower." ; exit 1)
