[ci] better bash

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -93,5 +93,8 @@ jobs:
         current_score=$(curl --silent https://hugsy.github.io/gef/coverage/gef_py.html | grep pc_cov | sed 's?.*<span class="pc_cov">\([^%]*\)%</span>?\1?g')
         bash scripts/generate-coverage-docs.sh
         new_score=$(cat docs/coverage/gef_py.html | grep pc_cov | sed 's?.*<span class="pc_cov">\([^%]*\)%</span>?\1?g')
-        echo "Test coverage score: ${new_score}% (old ${current_score}%)"
-        test ${current_score} -gt ${new_score} && (echo "New score cannot be lower." ; exit 1)
+        echo "Test coverage score: ${new_score}% (current ${current_score}%)"
+        if [ "${new_score}" -lt "${current_score}" ]; then
+          echo "New score cannot be lower."
+          exit 1
+        fi
